package game.pokemon;

public enum Move {
    POISON_ACID("Poison Acid", Type.POISON, 11, 10, 2, false),
    AIR_SLASH("Air Slash", Type.FLYING, 12, 8, 2, false),
    ASTONISH("Astonish", Type.GHOST, 7, 13, 2, false),
    ACID("ACID", Type.POISON, 10, 10, 2, false),
    BITE("Bite", Type.DARK, 6, 4, 1, false),
    BUBBLE("Bubble", Type.WATER, 10, 12, 2, false),
    BUG_BITE("Bug Bite", Type.BUG, 5, 6, 1, false),
    BULLET_PUNCH("Bullet Punch", Type.STEEL, 10, 11, 2, false),
    BULLET_SEED("Bullet Seed", Type.GRASS, 7, 13, 2, false),
    CHARGE_BEAM("Charge Beam", Type.ELECTRIC, 7, 14, 2, false),
    CHARM("Charm", Type.FAIRY, 20, 11, 3, false),
    CONFUSION("Confusion", Type.PSYCHIC, 19, 14, 3, false),
    COUNTER("Counter", Type.FIGHTING, 13, 9, 2, false),
    CUT("Cut", Type.NORMAL, 5, 5, 1, false),
    DOUBLE_KICK("Double Kick", Type.FIGHTING, 10, 13, 2, false),
    DRAGON_BREATH("Dragon Breath", Type.DRAGON, 6, 4, 1, false),
    DRAGON_TAIL("Dragon Tail", Type.DRAGON, 14, 8, 2, false),
    EMBER("Ember", Type.FIRE, 10, 10, 2, false),
    EXTRASENSORY("Extrasensory", Type.PSYCHIC, 11, 11, 2, false),
    FAIRY_WIND("Fairy Wind", Type.FAIRY, 9, 13, 2, false),
    FEINT_ATTACK("Feint Attack", Type.DARK, 11, 10, 2, false),
    FIRE_FANG("Fire Fang", Type.FIRE, 13, 9, 2, false),
    FIRE_SPIN("Fire Spin", Type.FIRE, 13, 9, 2, false),
    FORCE_PALM("Force Palm", Type.FIGHTING, 10, 16, 2, false),
    FROST_BREATH("Frost Breath", Type.ICE, 11, 9, 2, false),
    FURY_CUTTER("Fury Cutter", Type.BUG, 4, 8, 1, false),
    GEOMANCY("Geomancy", Type.FAIRY, 20, 14, 3, false),
    GUST("Gust", Type.FLYING, 25, 20, 4, false),
    HEX("Hex", Type.GHOST, 8, 13, 2, false),
    HIDDEN_POWER("Hidden Power", Type.NORMAL, 15, 15, 3, false),
    ICE_FANG("Ice Fang", Type.ICE, 12, 20, 3, false),
    ICE_SHARD("Ice Shard", Type.ICE, 10, 10, 2, false),
    INCINERATE("Incinerate", Type.FIRE, 32, 22, 5, false),
    INFESTATION("Infestation", Type.BUG, 9, 13, 2, false),
    IRON_TAIL("Iron Tail", Type.STEEL, 14, 6, 2, false),
    KARATE_CHOP("Karate Chop", Type.FIGHTING, 10, 13, 2, false),
    LEAFAGE("Leafage", Type.GRASS, 6, 4, 1, false),
    LICK("Lick", Type.GHOST, 5, 6, 1, false),
    LOCK_ON("Lock-On", Type.NORMAL, 2, 10, 1, false),
    LOW_KICK("Low Kick", Type.FIGHTING, 5, 5, 1, false),
    MAGICAL_LEAF("Magical Leaf", Type.GRASS, 17, 17, 3, false),
    METAL_CLAW("Metal Claw", Type.STEEL, 6, 5, 1, false),
    METAL_SOUND("Metal Sound", Type.STEEL, 4, 6, 1, false),
    MUD_SHOT("Mud Shot", Type.GROUND, 4, 6, 1, false),
    MUD_SLAP("Mud-Slap", Type.GROUND, 19, 13, 3, false),
    PECK("Peck", Type.FLYING, 10, 10, 2, false),
    POISON_JAB("Poison Jab", Type.POISON, 13, 9, 2, false),
    POISON_STING("Poison Sting", Type.POISON, 4, 6, 1, false),
    POUND("Pound", Type.NORMAL, 6, 5, 1, false),
    POWDER_SNOW("Powder Snow", Type.ICE, 6, 15, 2, false),
    PRESENT("Present", Type.NORMAL, 6, 23, 3, false),
    PSYCHO_CUT("Psycho Cut", Type.PSYCHIC, 4, 7, 1, false),
    PSYWAVE("Psywave", Type.PSYCHIC, 4, 7, 1, false),
    QUICK_ATTACK("Quick Attack", Type.NORMAL, 10, 13, 2, false),
    RAZOR_LEAF("Razor Leaf", Type.GRASS, 13, 7, 2, false),
    ROCK_SMASH("Rock Smash", Type.FIGHTING, 17, 12, 3, false),
    ROCK_THROW("Rock Throw", Type.ROCK, 13, 8, 2, false),
    ROLLOUT("Rollout", Type.ROCK, 15, 19, 3, false),
    SAND_ATTACK("Sand Attack", Type.GROUND, 4, 7, 1, false),
    SCRATCH("Scratch", Type.NORMAL, 6, 4, 1, false),
    SHADOW_CLAW("Shadow Claw", Type.GHOST, 6, 4, 1, false),
    SMACK_DOWN("Smack Down", Type.ROCK, 13, 7, 2, false),
    SNARL("Snarl", Type.DARK, 11, 13, 2, false),
    SPARK("Spark", Type.ELECTRIC, 4, 6, 1, false),
    SPLASH("Splash", Type.WATER, 0, 17, 3, false),
    STEEL_WING("Steel Wing", Type.STEEL, 14, 8, 2, false),
    STRUGGLE_BUG("Struggle Bug", Type.BUG, 15, 15, 3, false),
    SUCKER_PUNCH("Sucker Punch", Type.DARK, 5, 6, 1, false),
    TACKLE("Tackle", Type.NORMAL, 5, 5, 1, false),
    TAKE_DOWN("Take Down", Type.NORMAL, 7, 8, 2, false),
    THUNDER_FANG("Thunder Fang", Type.ELECTRIC, 10, 13, 2, false),
    THUNDER_SHOCK("Thunder Shock", Type.ELECTRIC, 4, 7, 1, false),
    TRANSFORM("Transform", Type.NORMAL, 0, 0, 4, false),
    VINE_WHIP("Vine Whip", Type.GRASS, 6, 5, 1, false),
    VOLT_SWITCH("Volt Switch", Type.ELECTRIC, 13, 20, 3, false),
    WATER_GUN("Water Gun", Type.WATER, 5, 5, 1, false),
    WATER_SHURIKEN("Water Shuriken", Type.WATER, 9, 14, 2, false),
    WATERFALL("Waterfall", Type.WATER, 13, 7, 2, false),
    WING_ATTACK("Wing Attack", Type.FLYING, 10, 11, 2, false),
    YAWN("Yawn", Type.NORMAL, 0, 13, 3, false),
    ZEN_HEADBUTT("Zen Headbutt", Type.PSYCHIC, 11, 9, 2, false),
    ACID_SPRAY("Acid Spray", Type.POISON, 20, 50, 6, true),
    ACROBATICS("Acrobatics", Type.FLYING, 100, 100, 4, true),
    AERIAL_ACE("Aerial Ace", Type.FLYING, 55, 33, 5, true),
    AEROBLAST("Aeroblast", Type.FLYING, 180, 100, 7, true),
    AIR_CUTTER("Air Cutter", Type.FLYING, 55, 50, 5, true),
    ANCIENT_POWER("Ancient Power", Type.ROCK, 70, 33, 7, true),
    AQUA_JET("Aqua Jet", Type.WATER, 45, 33, 5, true),
    AQUA_STEP("Aqua Step", Type.WATER, 55, 33, 7, true),
    AQUA_TAIL("Aqua Tail", Type.WATER, 50, 33, 4, true),
    AURA_SPHERE("Aura Sphere", Type.FIGHTING, 100, 50, 4, true),
    AURORA_BEAM("Aurora Beam", Type.ICE, 80, 50, 7, true),
    AVALANCHE("Avalanche", Type.ICE, 85, 50, 5, true),
    BEHEMOTH_BASH("Behemoth Bash", Type.STEEL, 125, 50, 3, true),
    BEHEMOTH_BLADE("Behemoth Blade", Type.STEEL, 200, 100, 7, true),
    BLAST_BURN("Blast Burn", Type.FIRE, 120, 50, 7, true),
    BLAZE_KICK("Blaze Kick", Type.FIRE, 40, 33, 2, true),
    BLEAKWIND_STORM("Bleakwind Storm", Type.FLYING, 150, 100, 5, true),
    BLIZZARD("Blizzard", Type.ICE, 130, 100, 6, true),
    BODY_SLAM("Body Slam", Type.NORMAL, 50, 33, 4, true),
    BONE_CLUB("Bone Club", Type.GROUND, 40, 33, 3, true),
    BOOMBURST("Boomburst", Type.NORMAL, 150, 100, 5, true),
    BRAVE_BIRD("Brave Bird", Type.FLYING, 130, 100, 4, true),
    BREAKING_SWIPE("Breaking Swipe", Type.DRAGON, 45, 33, 2, true),
    BRICK_BREAK("Brick Break", Type.FIGHTING, 40, 33, 3, true),
    BRINE("Brine", Type.WATER, 65, 50, 5, true),
    BRUTAL_SWING("Brutal Swing", Type.DARK, 65, 33, 4, true),
    BUBBLE_BEAM("Bubble Beam", Type.WATER, 45, 33, 4, true),
    BUG_BUZZ("Bug Buzz", Type.BUG, 95, 50, 7, true),
    BULLDOZE("Bulldoze", Type.GROUND, 80, 50, 7, true),
    CLANGING_SCALES("Clanging Scales", Type.DRAGON, 120, 100, 6, true),
    CLOSE_COMBAT("Close Combat", Type.FIGHTING, 105, 100, 5, true),
    CRABHAMMER("Crabhammer", Type.WATER, 85, 50, 4, true),
    CROSS_CHOP("Cross Chop", Type.FIGHTING, 50, 50, 3, true),
    CROSS_POISON("Cross Poison", Type.POISON, 40, 33, 3, true),
    CRUNCH("Crunch", Type.DARK, 65, 33, 6, true),
    CRUSH_CLAW("Crush Claw", Type.NORMAL, 0, 0, 4, true),
    CRUSH_GRIP("Crush Grip", Type.NORMAL, 210, 100, 3, true),
    DARK_PULSE("Dark Pulse", Type.DARK, 80, 50, 6, true),
    DARKEST_LARIAT("Darkest Lariat", Type.DARK, 80, 50, 4, true),
    DAZZLING_GLEAM("Dazzling Gleam", Type.FAIRY, 100, 50, 7, true),
    DIG("Dig", Type.GROUND, 100, 50, 9, true),
    DISARMING_VOICE("Disarming Voice", Type.FAIRY, 70, 33, 8, true),
    DISCHARGE("Discharge", Type.ELECTRIC, 65, 33, 5, true),
    DOOM_DESIRE("Doom Desire", Type.STEEL, 65, 33, 3, true),
    DOUBLE_IRON_BASH("Double Iron Bash", Type.STEEL, 70, 33, 4, true),
    DRACO_METEOR("Draco Meteor", Type.DRAGON, 150, 100, 7, true),
    DRAGON_ASCENT("Dragon Ascent", Type.FLYING, 140, 50, 7, true),
    DRAGON_CLAW("Dragon Claw", Type.DRAGON, 45, 33, 3, true),
    DRAGON_ENERGY("Dragon Energy", Type.DRAGON, 155, 50, 6, true),
    DRAGON_PULSE("Dragon Pulse", Type.DRAGON, 90, 50, 7, true),
    DRAIN_PUNCH("Drain Punch", Type.FIGHTING, 50, 33, 5, true),
    DRAINING_KISS("Draining Kiss", Type.FAIRY, 60, 50, 5, true),
    DRILL_PECK("Drill Peck", Type.FLYING, 70, 33, 5, true),
    DRILL_RUN("Drill Run", Type.GROUND, 85, 50, 6, true),
    DYNAMIC_PUNCH("Dynamic Punch", Type.FIGHTING, 85, 50, 5, true),
    EARTH_POWER("Earth Power", Type.GROUND, 100, 50, 7, true),
    EARTHQUAKE("Earthquake", Type.GROUND, 140, 100, 7, true),
    ENERGY_BALL("Energy Ball", Type.GRASS, 90, 50, 8, true),
    FEATHER_DANCE("Feather Dance", Type.FLYING, 35, 50, 6, true),
    FELL_STINGER("Fell Stinger", Type.BUG, 45, 33, 4, true),
    FIRE_BLAST("Fire Blast", Type.FIRE, 140, 100, 8, true),
    FIRE_PUNCH("Fire Punch", Type.FIRE, 50, 33, 4, true),
    FISSURE("Fissure", Type.GROUND, 9001, 25, 6, true),
    FLAME_BURST("Flame Burst", Type.FIRE, 70, 50, 5, true),
    FLAME_CHARGE("Flame Charge", Type.FIRE, 70, 33, 8, true),
    FLAME_WHEEL("Flame Wheel", Type.FIRE, 55, 50, 5, true),
    FLAMETHROWER("Flamethrower", Type.FIRE, 65, 50, 4, true),
    FLASH_CANNON("Flash Cannon", Type.STEEL, 100, 100, 5, true),
    FLOWER_TRICK("Flower Trick", Type.GRASS, 75, 33, 5, true),
    FLY("Fly", Type.FLYING, 90, 50, 4, true),
    FLYING_PRESS("Flying Press", Type.FIGHTING, 115, 50, 5, true),
    FOCUS_BLAST("Focus Blast", Type.FIGHTING, 140, 100, 7, true),
    FOUL_PLAY("Foul Play", Type.DARK, 70, 50, 4, true),
    FREEZE_SHOCK("Freeze Shock", Type.ICE, 160, 100, 3, true),
    FRENZY_PLANT("Frenzy Plant", Type.GRASS, 100, 50, 5, true),
    FRUSTRATION("Frustration", Type.NORMAL, 10, 33, 4, true),
    FUSION_BOLT("Fusion Bolt", Type.ELECTRIC, 140, 100, 4, true),
    FUSION_FLARE("Fusion Flare", Type.FIRE, 140, 100, 4, true),
    FUTURE_SIGHT("Future Sight", Type.PSYCHIC, 115, 100, 5, true),
    GIGA_DRAIN("Giga Drain", Type.GRASS, 50, 100, 8, true),
    GIGA_IMPACT("Giga Impact", Type.NORMAL, 200, 100, 9, true),
    GLACIATE("Glaciate", Type.ICE, 160, 100, 5, true),
    GRASS_KNOT("Grass Knot", Type.GRASS, 90, 50, 5, true),
    GUNK_SHOT("Gunk Shot", Type.POISON, 130, 100, 6, true),
    GYRO_BALL("Gyro Ball", Type.STEEL, 85, 50, 7, true),
    HEART_STAMP("Heart Stamp", Type.PSYCHIC, 40, 33, 4, true),
    HEAT_WAVE("Heat Wave", Type.FIRE, 95, 100, 6, true),
    HEAVY_SLAM("Heavy Slam", Type.STEEL, 70, 50, 4, true),
    HIGH_HORSEPOWER("High Horsepower", Type.GROUND, 105, 100, 3, true),
    HIGH_JUMP_KICK("High Jump Kick", Type.FIGHTING, 90, 100, 3, true),
    HORN_ATTACK("Horn Attack", Type.NORMAL, 45, 33, 4, true),
    HORN_DRILL("Horn Drill", Type.NORMAL, 9000, 25, 4, true),
    HURRICANE("Hurricane", Type.FLYING, 105, 100, 5, true),
    HYDRO_CANNON("Hydro Cannon", Type.WATER, 90, 50, 4, true),
    HYDRO_PUMP("Hydro Pump", Type.WATER, 135, 100, 7, true),
    HYDRO_PUMP_ALT("Hydro Pump", Type.WATER, 90, 100, 9, true),
    HYPER_BEAM("Hyper Beam", Type.NORMAL, 150, 100, 8, true),
    HYPER_FANG("Hyper Fang", Type.NORMAL, 80, 50, 5, true),
    ICE_BEAM("Ice Beam", Type.ICE, 95, 50, 7, true),
    ICE_BURN("Ice Burn", Type.ICE, 90, 50, 4, true),
    ICE_PUNCH("Ice Punch", Type.ICE, 50, 33, 4, true),
    ICICLE_SPEAR("Icicle Spear", Type.ICE, 55, 33, 4, true),
    ICY_WIND("Icy Wind", Type.ICE, 65, 33, 7, true),
    IRON_HEAD("Iron Head", Type.STEEL, 60, 50, 4, true),
    LAST_RESORT("Last Resort", Type.NORMAL, 90, 50, 6, true),
    LEAF_BLADE("Leaf Blade", Type.GRASS, 70, 33, 5, true),
    LEAF_STORM("Leaf Storm", Type.GRASS, 130, 100, 5, true),
    LEAF_TORNADO("Leaf Tornado", Type.GRASS, 45, 33, 6, true),
    LEECH_LIFE("Leech Life", Type.BUG, 0, 0, 5, true),
    LIQUIDATION("Liquidation", Type.WATER, 70, 33, 6, true),
    LOW_SWEEP("Low Sweep", Type.FIGHTING, 40, 33, 4, true),
    LUNGE("Lunge", Type.BUG, 55, 33, 6, true),
    LUSTER_PURGE("Luster Purge", Type.PSYCHIC, 100, 100, 3, true),
    MAGMA_STORM("Magma Storm", Type.FIRE, 75, 33, 5, true),
    MAGNET_BOMB("Magnet Bomb", Type.STEEL, 75, 33, 6, true),
    MEGA_DRAIN("Mega Drain", Type.GRASS, 25, 50, 5, true),
    MEGAHORN("Megahorn", Type.BUG, 105, 100, 4, true),
    METEOR_BEAM("Meteor Beam", Type.ROCK, 140, 100, 4, true),
    METEOR_MASH("Meteor Mash", Type.STEEL, 100, 50, 5, true),
    MIRROR_COAT("Mirror Coat", Type.PSYCHIC, 60, 50, 5, true),
    MIRROR_SHOT("Mirror Shot", Type.STEEL, 50, 33, 5, true),
    MIST_BALL("Mist Ball", Type.PSYCHIC, 105, 100, 4, true),
    MOONBLAST("Moonblast", Type.FAIRY, 130, 100, 8, true),
    MOONGEIST_BEAM("Moongeist Beam", Type.GHOST, 230, 100, 6, true),
    MUD_BOMB("Mud Bomb", Type.GROUND, 60, 33, 5, true),
    MUDDY_WATER("Muddy Water", Type.WATER, 45, 33, 4, true),
    MYSTICAL_FIRE("Mystical Fire", Type.FIRE, 60, 33, 4, true),
    NATURES_MADNESS("Natures Madness", Type.FAIRY, 90, 50, 4, true),
    NIGHT_SHADE("Night Shade", Type.GHOST, 60, 50, 5, true),
    NIGHT_SLASH("Night Slash", Type.DARK, 45, 33, 4, true),
    OBLIVION_WING("Oblivion Wing", Type.FLYING, 85, 50, 4, true),
    OBSTRUCT("Obstruct", Type.DARK, 20, 33, 3, true),
    OCTAZOOKA("Octazooka", Type.WATER, 55, 50, 5, true),
    OMINOUS_WIND("Ominous Wind", Type.GHOST, 55, 33, 5, true),
    ORIGIN_PULSE("Origin Pulse", Type.WATER, 120, 100, 3, true),
    OUTRAGE("Outrage", Type.DRAGON, 110, 50, 8, true),
    OVERHEAT("Overheat", Type.FIRE, 160, 100, 8, true),
    PARABOLIC_CHARGE("Parabolic Charge", Type.ELECTRIC, 70, 50, 6, true),
    PAYBACK("Payback", Type.DARK, 95, 100, 4, true),
    PETAL_BLIZZARD("Petal Blizzard", Type.GRASS, 110, 100, 5, true),
    PLAY_ROUGH("Play Rough", Type.FAIRY, 90, 50, 6, true),
    POISON_FANG("Poison Fang", Type.POISON, 30, 33, 3, true),
    POLTERGEIST("Poltergeist", Type.GHOST, 140, 100, 7, true),
    POWER_GEM("Power Gem", Type.ROCK, 80, 50, 6, true),
    POWER_WHIP("Power Whip", Type.GRASS, 90, 50, 5, true),
    POWER_UP_PUNCH("Power-Up Punch", Type.FIGHTING, 50, 33, 4, true),
    PRECIPICE_BLADES("Precipice Blades", Type.GROUND, 120, 100, 3, true),
    PSYBEAM("Psybeam", Type.PSYCHIC, 65, 50, 6, true),
    PSYCHIC("Psychic", Type.PSYCHIC, 95, 50, 6, true),
    PSYCHIC_FANGS("Psychic Fangs", Type.PSYCHIC, 25, 33, 2, true),
    PSYCHO_BOOST("Psycho Boost", Type.PSYCHIC, 70, 50, 8, true),
    PSYSHOCK("Psyshock", Type.PSYCHIC, 60, 33, 5, true),
    PSYSTRIKE("Psystrike", Type.PSYCHIC, 95, 50, 5, true),
    RAGE_FIST("Rage Fist", Type.GHOST, 100, 50, 6, true),
    RAZOR_SHELL("Razor Shell", Type.WATER, 55, 33, 3, true),
    REST("Rest", Type.NORMAL, 50, 33, 4, true),
    RETURN("Return", Type.NORMAL, 25, 33, 1, true),
    ROAR_OF_TIME("Roar of Time", Type.DRAGON, 160, 100, 4, true),
    ROCK_BLAST("Rock Blast", Type.ROCK, 50, 33, 4, true),
    ROCK_SLIDE("Rock Slide", Type.ROCK, 75, 50, 5, true),
    ROCK_TOMB("Rock Tomb", Type.ROCK, 65, 50, 6, true),
    ROCK_WRECKER("Rock Wrecker", Type.ROCK, 110, 50, 7, true),
    SACRED_FIRE("Sacred Fire", Type.FIRE, 120, 100, 5, true),
    SACRED_SWORD("Sacred Sword", Type.FIGHTING, 50, 33, 2, true),
    SAND_TOMB("Sand Tomb", Type.GROUND, 60, 33, 8, true),
    SANDSEAR_STORM("Sandsear Storm", Type.GROUND, 150, 100, 5, true),
    SCALD("Scald", Type.WATER, 75, 50, 7, true),
    SCALD_ALT("Scald", Type.WATER, 50, 100, 9, true),
    SCORCHING_SANDS("Scorching Sands", Type.GROUND, 90, 50, 6, true),
    SEED_BOMB("Seed Bomb", Type.GRASS, 55, 33, 4, true),
    SEED_FLARE("Seed Flare", Type.GRASS, 115, 100, 5, true),
    SHADOW_BALL("Shadow Ball", Type.GHOST, 100, 50, 6, true),
    SHADOW_BONE("Shadow Bone", Type.GHOST, 85, 50, 6, true),
    SHADOW_FORCE("Shadow Force", Type.GHOST, 140, 100, 4, true),
    SHADOW_PUNCH("Shadow Punch", Type.GHOST, 35, 33, 3, true),
    SHADOW_SNEAK("Shadow Sneak", Type.GHOST, 50, 33, 6, true),
    SIGNAL_BEAM("Signal Beam", Type.BUG, 75, 50, 6, true),
    SILVER_WIND("Silver Wind", Type.BUG, 65, 33, 7, true),
    SKULL_BASH("Skull Bash", Type.NORMAL, 130, 100, 6, true),
    SKY_ATTACK("Sky Attack", Type.FLYING, 80, 50, 4, true),
    SLUDGE("Sludge", Type.POISON, 50, 33, 4, true),
    SLUDGE_BOMB("Sludge Bomb", Type.POISON, 85, 50, 5, true),
    SLUDGE_WAVE("Sludge Wave", Type.POISON, 105, 100, 6, true),
    SOLAR_BEAM("Solar Beam", Type.GRASS, 180, 100, 10, true),
    SPACIAL_REND("Spacial Rend", Type.DRAGON, 160, 100, 5, true),
    SPARKLING_ARIA("Sparkling Aria", Type.WATER, 85, 33, 6, true),
    SPIRIT_SHACKLE("Spirit Shackle", Type.GHOST, 70, 33, 5, true),
    STOMP("Stomp", Type.NORMAL, 50, 50, 3, true),
    STONE_EDGE("Stone subst", Type.ROCK, 105, 100, 5, true),
    STRUGGLE("Struggle", Type.NORMAL, 35, 0, 4, true),
    SUBMISSION("Submission", Type.FIGHTING, 55, 50, 4, true),
    SUNSTEEL_STRIKE("Sunsteel Strike", Type.STEEL, 230, 100, 6, true),
    SUPERPOWER("Superpower", Type.FIGHTING, 85, 50, 6, true),
    SURF("Surf", Type.WATER, 60, 50, 3, true),
    SWIFT("Swift", Type.NORMAL, 65, 50, 6, true),
    SYNCHRONOISE("Synchronoise", Type.PSYCHIC, 80, 50, 5, true),
    THUNDER("Thunder", Type.ELECTRIC, 100, 100, 5, true),
    THUNDER_CAGE("Thunder Cage", Type.ELECTRIC, 220, 100, 6, true),
    THUNDER_PUNCH("Thunder Punch", Type.ELECTRIC, 50, 33, 4, true),
    THUNDERBOLT("Thunderbolt", Type.ELECTRIC, 80, 50, 5, true),
    TORCH_SONG("Torch Song", Type.FIRE, 100, 50, 7, true),
    TRAILBLAZE("Trailblaze", Type.GRASS, 65, 50, 4, true),
    TRI_ATTACK("Tri Attack", Type.NORMAL, 75, 50, 5, true),
    TRIPLE_AXEL("Triple Axel", Type.ICE, 60, 33, 4, true),
    TWISTER("Twister", Type.DRAGON, 50, 33, 6, true),
    UPPER_HAND("Upper Hand", Type.FIGHTING, 50, 33, 4, true),
    V_CREATE("V-create", Type.FIRE, 105, 33, 6, true),
    VISE_GRIP("Vise Grip", Type.NORMAL, 35, 33, 4, true),
    VOLT_TACKLE("Volt Tackle", Type.ELECTRIC, 90, 33, 7, true),
    WATER_PULSE("Water Pulse", Type.WATER, 65, 50, 6, true),
    WILD_CHARGE("Wild Charge", Type.ELECTRIC, 90, 50, 5, true),
    WILDBOLT_STORM("Wildbolt Storm", Type.ELECTRIC, 150, 100, 5, true),
    WRAP_NORMAL("Wrap", Type.NORMAL, 60, 33, 6, true),
    WRAP_ALT("Wrap", Type.NORMAL, 25, 33, 6, true),
    X_SCISSOR("X-Scissor", Type.BUG, 45, 33, 3, true),
    ZAP_CANNON("Zap Cannon", Type.ELECTRIC, 140, 100, 7, true);

    private final String name;
    private final Type type;
    private final int power;
    private final int energy;
    private final int cooldown;
    private final boolean isCharged;

    Move(String name, Type type, int power, int energy, int cooldown, boolean isCharged) {
        this.name = name;
        this.type = type;
        this.power = power;
        this.energy = energy;
        this.cooldown = cooldown;
        this.isCharged = isCharged;
    }

    public String getName() {
        return name;
    }

    public Type getType() {
        return type;
    }

    public int getPower() {
        return power;
    }

    public int getEnergy() {
        return energy;
    }

    public boolean isCharged() {
        return isCharged;
    }

    public int getCooldown() {
        return cooldown;
    }
}